### ISSUE TITLE
Log arguments of tasks

### ISSUE THREAD

**Issue by pawelgalazka** [pawelgalazka/runjs#24]
When user call a task with arguments or other task will be called with arguments along the process, in the terminal there will be reported that certain task was run without any information about the arguments which were passed to it. It would be good to provide that information.

**Comment by karuppiah7890** [comment]
You mean, arguments passed to user defined tasks in the runfile.js ?

**Comment by pawelgalazka** [comment]
@karuppiah7890 I've updated description, take a look

**Comment by karuppiah7890** [comment]
Okay! 
So, whenever a task (because of another task or directly by the user) is executed, we need to log it's arguments to help the user understand if correct input was given to the tasks. 

I think I will take this up. But for now, I am trying to understand the /lib/index.js file and by the way, I am also trying to use some new ES6 features in it. Like the spread syntax instead of using apply(), and then template literals, and some more stuff. Shall I proceed ? Or you will make those changes yourself ?

**Comment by pawelgalazka** [comment]
Go ahead 👍

**Comment by karuppiah7890** [comment]
@pawelgalazka Hey, looks like you have two index.js files. One compiling to the other using babel. Why are we compiling and then using the compiled version ? I see that only the import and export constructs won't work in node, so they have to be transpiled, but other constructs like arrow functions, default parameters do work, as far as I know.

**Comment by pawelgalazka** [comment]
@karuppiah7890 we do want to support node >=4.x, a lot of ES6 features is not available there

**Comment by karuppiah7890** [comment]
Oh, Okay. I didn't know. Sorry

**Comment by pawelgalazka** [comment]
No worries mate! 🙂
