### ISSUE TITLE
options argument

### ISSUE THREAD

**Issue by ivan-kleshnin** [pawelgalazka/runjs#75]
Hi Pawel. The projects is really nice except that `options(this)` style of getting optional args seems counter-intuitive and unconventional to me.

Any chance it can be replaced with:

```
$ run -foo -bar

this.foo
this.bar
```

```
runfile[taskName].apply({ options }, params)
// vs
runfile[taskName].apply(options, params)
```

Do you plan to add more stuff to `this` except those `options`?

**Comment by pawelgalazka** [comment]
Hey @ivan-kleshnin yes, I made here assumption that having `this.options` will be less invasive that having each option on `this` object. True I don't strong arguments behind it, since there is not much of a case where putting options individually on `this` object could break user code and I don't plan to put anything else on `this` object. I don't have strong opinion on either case.

What I'm seriously considering though is passing options always as first argument to task function, even if there will be no options, task would receive empty object. It's even cleaner and less confusing when calling a task from other task (how to pass options). Still I haven't decided on that yet, since every task would need to have mandatory `options` first argument, which is a downside of this approach.

**Comment by ivan-kleshnin** [comment]
> What I'm seriously considering though is passing options always as first argument to task function, even if there will be no options, task would receive an empty object. It's even cleaner and less confusing when calling a task from other task (how to pass options). Still I haven't decided on that yet, since every task would need to have mandatory options first argument, which is a downside.

Yes, I also like "the normal argument" approach even better if we consider task dependencies. 
Personally, I have nothing against mandatory arguments – I'm a fan of currying and my APIs
look like `run({}, ...)` quite often. 

On opportunity to ask – do you plan to replace `help` with something more sophisticated in future (annotations of required args, maybe even their types, etc) or do you plan to keep this stuff on the user side. **JS community seriously needs a better Commander!**

Something like:

```js
let required = (x) => x ? "Need x" ... : false 
// Any validation library: Tcomb / JSONScheme / IoTS 
// can be reduced to this with little or no code
// avoiding vendor lock-ins.

function deploy(target) {
  ...
}

export annotate(deploy, {
  params: [
    ['target', required], // accept basic ("errorMessage" | false) style validators
    ...
  ],
  options: {
    watch: ['run tests in a watch mode', required] // --//--
    ...
  },
})
```

**Comment by pawelgalazka** [comment]
For now I do not plan to make `help` more sophisticated. Naturally it feels like it should be mostly a job for type system regarding such validations. Like we should be able to use type system for most of this. For example:

```js
function deploy (options: { watch: boolean }, target: string | boolean) {

}
```

Nice and clean. That would require unfortunately mandatory transpilation process which I don't want to introduce (slows down running tasks).

**Comment by pawelgalazka** [comment]
@ivan-kleshnin what might possible today with current version of runjs is using https://codemix.github.io/flow-runtime/#/ and setting it up with babel for runjs.

**Comment by ivan-kleshnin** [comment]
Yes, makes sense. I remember I saw something like that for TypeScript as well, though may be wrong.

**Comment by pawelgalazka** [comment]
Closing this one in favour of https://github.com/pawelgalazka/runjs/issues/77
