### ISSUE TITLE
Dropping support for TypeScript and Babel

### ISSUE THREAD

**Issue by pawelgalazka** [pawelgalazka/runjs#76]
For version 5 I'm seriously considering dropping support for TypeScript and Babel transpilers. Normally you can run runjs tasks from pure node runfile but it is possible to transpile in a fly runfile through Babel or TypeScript. This unfortunately slows down runjs and doesn't seems to be that practical and used, as runjs tasks doesn't normally interact with "app code" which may use those tools. That's why I'm considering removing code which allows to use Babel or TS.

If you don't agree. Please speak up, I wanna give this up for discussion.

**Comment by ivan-kleshnin** [comment]
I'd like to import ES6 modules occasionally. If we consider validation possibilites those can be expressed as types and types are often shared, like some `Id` type can be used in both CLI and Frontend and Backend.

Is it possible to make `npx` run `babel-node` instead of just `node`? That could be an easier solution for both TS / Babel and whatever else, not requiring any additional code in RunJS.

**Comment by ljani** [comment]
I'm using TypeScript to write my scripts. Though I'm happy to run `ts-node` separately as long as it's still possible and I can point `runjs` to a file with `.ts` extension.

What do we gain if the functionality is removed? The code for [`requires`](https://github.com/pawelgalazka/runjs/blob/834b520b70e0523e90411042c3116a24d44aa5be/src/script.js#L44-L49) doesn't seem to be complex, so maintenance overhead is probably minimal and checking if it exists probably won't kill your performance. I'd say let the users worry about the performance, if they have problems using the transpilers.

**Comment by pawelgalazka** [comment]
Closing this one, with pretty good summary above ^
